
// Objective-C API for talking to the following Go packages
//
//	fiskaly.com/sma/mobile/ios
//
// File is generated by gomobile bind. Do not edit.
#ifndef __FiskalyKassensichvSma_FRAMEWORK_H__
#define __FiskalyKassensichvSma_FRAMEWORK_H__

#include "FiskalyKassensichvSma.objc.h"
#include "Universe.objc.h"

#endif
