// Objective-C API for talking to fiskaly.com/sma/mobile/ios Go package.
//   gobind -lang=objc fiskaly.com/sma/mobile/ios
//
// File is generated by gobind. Do not edit.

#ifndef __FiskalyKassensichvSma_H__
#define __FiskalyKassensichvSma_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull FiskalyKassensichvSmaInvoke(NSString* _Nullable request);

#endif
